version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: conflict_check
    ports:
      - "3306:3306"

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    ports:
      - "3001:3000"
    depends_on:
      - mysql
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
